spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gaplaut2
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: create-drop