POST http://localhost:8080/api/centres
Content-Type: application/json

{
    "id": 3,
    "centreName": "El Grando Centrissimo",
    "city": "3"
}

###
GET http://localhost:8080/api/centres

###
GET http://localhost:8080/api/centre/3




###
POST http://localhost:8080/api/doctors
Content-Type: application/json

{
    "id": 2,
    "lastName": "PLAUT",
    "firstName": "Tristan",
    "centre": {
        "id": 1
    }
}

###
GET http://localhost:8080/api/doctors

###
GET http://localhost:8080/api/doctor/2