POST http://localhost:8080/centres
Content-Type: application/json

{
    "id": 1,
    "centreName": "El Grando Centrissimo",
    "city": "Marseille"
}

###

POST http://localhost:8080/doctors
Content-Type: application/json

{
    "id": 1,
    "lastName": "GERMAIN",
    "firstName": "Stéphane",
    "centre": {
        "id": 1
    }
}

###
POST http://localhost:8080/doctors
Content-Type: application/json

{
    "id": 2,
    "lastName": "SAVOY",
    "firstName": "Delphine",
    "centre": {
        "id": 2
    }
}