POST http://localhost:8080/public/api/centres
Content-Type: application/json

{
    "centreName": "El Grando Centrissimo Cinque",
    "city": "City 5",
    "address": "5 rue de la 5ème ville",
    "postalCode": "55555"
}

###
POST http://localhost:8080/public/api/centres
Content-Type: application/json

{
    "centreName": "Centre de la vie",
    "city": "City Kratos",
    "address": "Rue de la vie",
    "postalCode": "00000"
}

###
GET http://localhost:8080/public/api/centres

###
GET http://localhost:8080/public/api/centre/2

###
POST http://localhost:8080/api/doctors
Content-Type: application/json

{
    "lastName": "Nataf",
    "firstName": "David",
    "centre": {
        "id": 1
    }
}

###
GET http://localhost:8080/api/doctors

###
GET http://localhost:8080/api/doctor/2

### Vaccination
    # private String mail;
    # private String phoneNumber;
    # private String last_name;
    # private String first_name;
    # private LocalDateTime date;
###

POST http://localhost:8080/api/vaccinations
Content-Type: application/json

{
    
    "mail": "gagou@gmail.com",
    "phoneNumber": "0606060606",
    "last_name": "Gagou",
    "first_name": "Gagou",
    "date": "2021-12-12T12:12:12"
}

###public Doctor(Integer id, String lastName ,String firstName, Centre centre, String email, String password, List<Role> roles)
POST http://localhost:8080/public/api/doctors
Content-Type: application/json

{
    "lastName": "superadmin",
    "firstName": "superadmin",
    "centre": {
        "id": 1
    },
    "email": "superadmin",
    "password": "superadmin",
    "roles": [
        {
            "id": 1
        }
    ]

    
}

### Doctor Admin
POST http://localhost:8080/public/api/doctors
Content-Type: application/json

{
    "lastName": "admin",
    "firstName": "admin",
    "centre": {
        "id": 1
    },
    "email": "admin",
    "password": "admin",
    "roles": [
        {
            "id": 2
        }
    ]

    
}

### Doctor
POST http://localhost:8080/public/api/doctors
Content-Type: application/json

{
    "lastName": "médecin",
    "firstName": "médecin",
    "centre": {
        "id": 1
    },
    "email": "médecin",
    "password": "médecin",
    "roles": [
        {
            "id": 3
        }
    ]

    
}

### Basic Auth superadmin:superadmin
GET http://localhost:8080/private/api/roles
Content-Type: application/json
Authorization: Basic c3VwZXJhZG1pbjpzdXBlcmFkbWlu

### Basic Auth request with admin:admin
GET http://localhost:8080/private/api/roles
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### Basic Auth request with médecin:médecin
GET http://localhost:8080/private/api/roles
Content-Type: application/json
Authorization: Basic bcOpZGVjaW46bcOpZGVjaW4=

### Basic Auth request with false credentials
GET http://localhost:8080/private/api/roles
Content-Type: application/json
Authorization: Basic marchepas

